# report.yaml
---
- name: Save GRUB result to file
  copy:
    content: "{{ grub_result.stdout | default('') }}"
    dest: "{{ report_dir }}/{{ inventory_hostname }}_grub_result.log"
    mode: '0644'

- name: Save systemd reload result to file
  copy:
    content: "{{ reload_result.stdout | default('') }}"
    dest: "{{ report_dir }}/{{ inventory_hostname }}_systemd_reload.log"
    mode: '0644'

- name: Save playbook run log on host
  copy:
    content: "Playbook executed on {{ ansible_date_time.iso8601 }} by {{ ansible_user }}"
    dest: "{{ report_dir }}/{{ inventory_hostname }}_ansible_prereq_run.log"
    mode: '0644'