# report.yaml
---
- name: Ensure report directory exists
  file:
    path: "{{ report_dir }}"
    state: directory
    mode: '0755'

- name: Write summary report on remote host
  copy:
    dest: "{{ report_dir }}/{{ inventory_hostname }}_resize_summary.txt"
    content: |
      === Partition Resize ===
      {{ resizepart_output.stdout | default('N/A') }}

      === Partition Table ===
      {{ lsblk_output.stdout }}

      === PV Resize ===
      {{ pvresize_output.stdout | default('N/A') }}

      === LV Resize ===
      {{ lvresize_output.stdout | default('N/A') }}

      === Filesystem Resize ===
      {{ resizefs_output.stdout | default('N/A') }}

    mode: '0644'
