---
- name: Execute All System Configuration Roles
  hosts: all
  become: yes
  roles:
    - { role: package-update, tags: ['package-update'] }
    - { role: system-config, tags: ['system-config'] }
    - { role: resize-disk, tags: ['resize-disk'] }
    - { role: audit-logrotate, tags: ['audit-logrotate'] }
    - { role: apiserver-config, tags: ['apiserver-config'] }
    - { role: final-report, tags: ['final-report'] }
