---
# Tasks for testing and reporting logrotate status
- name: Test logrotate configuration
  command: logrotate -d /etc/logrotate.d/audit
  register: logrotate_test
  ignore_errors: yes

- name: Show logrotate test output
  debug:
    msg: "{{ logrotate_test.stdout_lines }}"

- name: Force log rotation
  command: logrotate -f /etc/logrotate.d/audit
  register: logrotate_force
  ignore_errors: yes

- name: Show forced log rotation output
  debug:
    msg: "{{ logrotate_force.stdout_lines }}"

- name: Restart logrotate service
  systemd:
    name: logrotate.timer
    state: restarted
    enabled: yes
