---
# Tasks for installing logrotate and configuring audit log rotation
- name: Ensure logrotate is installed
  apt:
    name: logrotate
    state: present

- name: Create logrotate configuration for audit logs
  copy:
    dest: "/etc/logrotate.d/audit"
    content: |
      /var/log/audit/audit.log {
          daily
          rotate 90
          maxage 90
          compress
          delaycompress
          missingok
          notifempty
          create 0640 root adm
          sharedscripts
          postrotate
              systemctl restart auditd.service > /dev/null
          endscript
      }
    owner: root
    group: root
    mode: '0644'
