# setup.yaml
---
- name: Create report directory if not exists
  file:
    path: "{{ report_dir }}"
    state: directory
    mode: '0755'

- name: Read /etc/hosts
  shell: cat /etc/hosts
  register: hosts_out

- name: Read /etc/sysctl.conf
  shell: cat /etc/sysctl.conf
  register: sysctl_out

- name: Read /etc/resolv.conf
  shell: cat /etc/resolv.conf
  register: resolv_out

- name: Read /etc/environment
  shell: cat /etc/environment
  register: env_out

- name: Read update_etc_hosts from cloud.cfg
  shell: grep -w update_etc_hosts /etc/cloud/cloud.cfg || true
  register: cloud_cfg_out

- name: Check partition info
  command: lsblk -o NAME,SIZE /dev/vda
  register: vda_check
  ignore_errors: yes

- name: Read /etc/apt/apt.conf.d/20auto-upgrades
  shell: cat /etc/apt/apt.conf.d/20auto-upgrades
  register: auto_upgrades_check
  ignore_errors: yes

- name: Check if net.ifnames=0 is already present in grub
  shell: grep -q 'net.ifnames=0' /etc/default/grub && echo 'Present' || echo 'Absent'
  register: grub_net_ifnames_check
  ignore_errors: yes