---
# Setup HTTP/HTTPS proxy configuration and perform package updates
- name: Check if HTTP proxy is already set
  ansible.builtin.shell: grep -q 'Acquire::http::Proxy' /etc/apt/apt.conf
  register: http_proxy_check
  ignore_errors: true
  changed_when: false

- name: Append HTTP proxy setting to /etc/apt/apt.conf if not present
  lineinfile:
    path: /etc/apt/apt.conf
    line: 'Acquire::http::Proxy "http://10.56.224.108:3128";'
    create: yes
    state: present
  when: http_proxy_check.rc != 0

- name: Check if HTTP proxy is already set
  ansible.builtin.shell: grep -q 'Acquire::https::Proxy' /etc/apt/apt.conf
  register: https_proxy_check
  ignore_errors: true
  changed_when: false

- name: Append HTTPS proxy setting to /etc/apt/apt.conf if not present
  lineinfile:
    path: /etc/apt/apt.conf
    line: 'Acquire::https::Proxy "http://10.56.224.108:3128";'
    create: yes
    state: present
  when: https_proxy_check.rc != 0

- name: Check if the user is root
  command: id -u
  register: user_id
  failed_when: user_id.stdout != "0"
  changed_when: false

- name: Update apt package manager
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
