---
- name: Execute All System Configuration Roles
  hosts: all
  become: yes
  roles:
    - { role: package-update, tags: ['package'] }
    - { role: system-config, tags: ['sysconfig'] }
    - { role: resize-disk, tags: ['resize'] }
    - { role: audit-logrotate, tags: ['logrotate'] }
    - { role: apiserver-config, tags: ['apiserver'] }
    - { role: final-report, tags: ['report'] }
