---
- name: Execute All System Configuration Roles
  hosts: all
  become: yes
  roles:
    - role: system-config
    - role: resize-disk
    - role: audit-logrotate
    - role: package-update
    - role: final-report
    - role: apiserver-config